### ISSUE TITLE
Crashes After Completing Interactive Setup

### ISSUE THREAD

**Issue by lots0logs** [ConorWilliams/rsinc#10]
Any idea what the problem could be? 

```
__________       .__
\______   \ _____|__| ____   ____
|       _//  ___/  |/    \_/ ___\
|    |   \\___ \|  |   |  \  \___
|____|_  /____  >__|___|  /\___  >
\/     \/        \/     \/

Copyright 2019 C. J. Williams (CHURCHILL COLLEGE)
This is free software with ABSOLUTELY NO WARRANTY

Don't have: ".", entering first_sync mode
Ignore: []
Crawling: "." ⠹2020/02/26 21:17:21 Failed to lsjson: error in ListJSON: directory not found
Traceback (most recent call last):
File "/usr/bin/rsinc", line 11, in <module>
load_entry_point('rsinc==2.13.dev0', 'console_scripts', 'rsinc')()
File "/usr/lib/python3.8/site-packages/rsinc/rsinc.py", line 236, in main
rmt = lsl(path_rmt, HASH_NAME)
File "/usr/lib/python3.8/site-packages/rsinc/rclone.py", line 95, in lsl
list_of_dicts = ujson.load(result.stdout)
ValueError: Expected object or value
```

**Comment by lots0logs** [comment]
So I'm guessing the problem is that I'm trying to have an entire directory synced as the root of my google drive but rsinc wants to be provided the names of the directories inside the root to sync. Is that correct? Does that mean what I want to do is not supported?

**Comment by ConorWilliams** [comment]
I think you are correct. Rsinc expects a directory inside each root to sync. In addition rsinc does not know how to expand `.` if you where to enter the empty string as the folder to sync it 'might' work as expected though.
