### ISSUE TITLE
crashes when running rsinc

### ISSUE THREAD

**Issue by luislozoya** [ConorWilliams/rsinc#15]
Hello I'm using a raspberry pi I already have installed rclone and its working fine, 
but when i try to run rsinc after installing  with pip3 install git+https://github.com/ConorWilliams/rsinc
I get the following error

# rsinc
Traceback (most recent call last):
  File "/usr/local/bin/rsinc", line 11, in <module>
    load_entry_point('rsinc==2.13.dev0', 'console_scripts', 'rsinc')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.local/lib/python3.5/site-packages/rsinc/rsinc.py", line 100
    "-v", "--version", action="version", version=f"rsinc version: {__version__}"
                                                                               ^
SyntaxError: invalid syntax

I also tried with rsinc --configure but i also get the same error

#rsinc --configure
Traceback (most recent call last):
  File "/usr/local/bin/rsinc", line 11, in <module>
    load_entry_point('rsinc==2.13.dev0', 'console_scripts', 'rsinc')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.local/lib/python3.5/site-packages/rsinc/rsinc.py", line 100
    "-v", "--version", action="version", version=f"rsinc version: {__version__}"
                                                                               ^
SyntaxError: invalid syntax

**Comment by ConorWilliams** [comment]
Hi there, thanks for opening an issue.

Rsinc uses python 3.6 f-Strings so it will not work with python 3.5. I will update the pip version requirements so that people dont run into this issue again. 

If you want to use rsinc you will have to update your python version (or submit a pull request providing backwards compatability!).

**Comment by luislozoya** [comment]
I intalled 3.6 and also did pip intall to f-strings but when i run it again i got this errors, I dont know what i could be missing

#python rsinc
Traceback (most recent call last):
  File "rsinc", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'rsinc==2.13.dev0' distribution was not found and is required by the application

**Comment by luislozoya** [comment]
I solved i

> 
> 
> I intalled 3.6 and also did pip intall to f-strings but when i run it again i got this errors, I dont know what i could be missing
> 
> #python rsinc
> Traceback (most recent call last):
> File "rsinc", line 6, in
> from pkg_resources import load_entry_point
> File "/usr/local/lib/python3.6/site-packages/pkg_resources/**init**.py", line 3088, in
> @_call_aside
> File "/usr/local/lib/python3.6/site-packages/pkg_resources/**init**.py", line 3072, in _call_aside
> f(*args, **kwargs)
> File "/usr/local/lib/python3.6/site-packages/pkg_resources/**init**.py", line 3101, in _initialize_master_working_set
> working_set = WorkingSet._build_master()
> File "/usr/local/lib/python3.6/site-packages/pkg_resources/**init**.py", line 574, in _build_master
> ws.require(**requires**)
> File "/usr/local/lib/python3.6/site-packages/pkg_resources/**init**.py", line 892, in require
> needed = self.resolve(parse_requirements(requirements))
> File "/usr/local/lib/python3.6/site-packages/pkg_resources/**init**.py", line 778, in resolve
> raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'rsinc==2.13.dev0' distribution was not found and is required by the application

Nevermind, i was trying with 3.6.3, it got solved when i install it with 3.6.8
