### ISSUE TITLE
Error setting up the synchronization

### ISSUE THREAD

**Issue by pastorpflores** [ConorWilliams/rsinc#19]
I've succesfully configured the rclone service with drive and I'm trying to set up the synchronization with rsinc.
I've configured rsinc with rsinc --config with the following parameters in the config.json:

{
    "BASE_L":"\/mnt\/Ubuntu_data\/Drive",
    "BASE_R":"gdrive:",
    "CASE_INSENSATIVE":true,
    "DEFAULT_DIRS":[
        "\/mnt\/Ubuntu_data\/Drive"
    ],
    "FAST_SAVE":false,
    "HASH_NAME":"MD5",
    "LOG_FOLDER":"\/home\/pablo\/.rsinc\/logs\/",
    "MASTER":"\/home\/pablo\/.rsinc\/master.json",
    "TEMP_FILE":"\/home\/pablo\/.rsinc\/rsinc.tmp"
}

and trying to star the process with rsinc --default and I obtain the following error:

Don't have: ".", entering first_sync mode
Ignore: []
Crawling: "." ⠼2020/10/21 12:17:53 Failed to lsjson: error in ListJSON: directory not found
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/rsinc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.8/site-packages/rsinc/rsinc.py", line 247, in main
    rmt = lsl(path_rmt, HASH_NAME)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/rsinc/rclone.py", line 95, in lsl
    list_of_dicts = ujson.load(result.stdout)
ValueError: Expected object or value

**Comment by ConorWilliams** [comment]
hmm, could you try navigating to `/mnt/Ubuntu_data/Drive` and typing `rsinc`

**Comment by pastorpflores** [comment]
I've tried, but the output is the same:

Don't have: ".", entering first_sync mode
Ignore: []
Crawling: "." ⠧2020/10/21 15:41:18 Failed to lsjson: error in ListJSON: directory not found
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/rsinc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.8/site-packages/rsinc/rsinc.py", line 247, in main
    rmt = lsl(path_rmt, HASH_NAME)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/rsinc/rclone.py", line 95, in lsl
    list_of_dicts = ujson.load(result.stdout)
ValueError: Expected object or value

**Comment by ConorWilliams** [comment]
It looks like the call to rclone's lsjson command is failing, does `rclone lsjson -R /mnt/Ubuntu_data/Drive` produce any output?

**Comment by pastorpflores** [comment]
Yes, it shows the list off all the files inside
