### ISSUE TITLE
Initial configuration fails

### ISSUE THREAD

**Issue by adrianf0** [ConorWilliams/rsinc#5]
As in the title, initial configuration fails on Ubuntu 18.04 LTS.

```
$>rsinc --v
Copyright 2019 C. J. Williams (CHURCHILL COLLEGE)
This is free software with ABSOLUTELY NO WARRANTY
rsinc version: 2.12-DEV

```
```
$> rsinc

Copyright 2019 C. J. Williams (CHURCHILL COLLEGE)
This is free software with ABSOLUTELY NO WARRANTY

Starting configuration mode
Path to local root folder i.e "~/": ~/Dokumenty
Local root is: /home/afiergol/Dokumenty

Path to remote root folder i.e "onedrive:": Dokumenty:
Remote root is: Dokumenty:

Finding a matching hash function...
Searching: /home/afiergol/Dokumenty
Searching: Dokumenty:
Traceback (most recent call last):
  File "/home/afiergol/.local/bin/rsinc", line 11, in <module>
    load_entry_point('rsinc==2.12.dev0', 'console_scripts', 'rsinc')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/afiergol/.local/lib/python3.6/site-packages/rsinc/rsinc.py", line 121, in <module>
    config_cli(config_path)
  File "/home/afiergol/.local/lib/python3.6/site-packages/rsinc/config.py", line 64, in config_cli
    common = lcl_hashes.intersection(rmt_hashes)
AttributeError: 'NoneType' object has no attribute 'intersection'
```

**Comment by ConorWilliams** [comment]
Is there at least one file in each of `/home/afiergol/Dokumenty` and `Dokumenty:`. This is requred so rsinc can request an rclone hash of each one and then find the itersecting hashes avaliable.

**Comment by adrianf0** [comment]
Thanks, that was the issue.
